### ISSUE TITLE
[TASK] Acceptance tests

### ISSUE THREAD

**Issue by kpamela** [kpamela/StudyRing#108]
No linked story.
Need to format an excel sheet with all stories for all sprints, and test the platform for each feature manually.

- [x] Sprint 1 Test
- [x] Sprint 2 Test
- [x] Sprint 3 Test
- [x] Sprint 4 Test
- [x] Sprint 5 Test

**Comment by taj-ch** [comment]
Acceptance test is done. Closing issue.
