### ISSUE TITLE
[Story] Login and registration page

### ISSUE THREAD

**Issue by Lordofsnails** [kpamela/StudyRing#11]
As a user, I would like to be able to connect to login to my personalized account with a username.

Tasks:
- [x] Setup registration page
Story points: 5
Priority: 1

- [x] Setup login and username/password database
Story points: 5
Priority: 1

**Comment by 85Arshad** [comment]
Front page added

**Comment by kpamela** [comment]
Added the login on the front page. Needs links to other 3Pages (Create and account and such)

**Comment by Zackkogan** [comment]
link to login is working but actual user database and login popup is not working properly

**Comment by kpamela** [comment]
#41  Login and registration functions
