### ISSUE TITLE
[BUG] Event creation not working

### ISSUE THREAD

**Issue by kpamela** [kpamela/StudyRing#112]
The "submit" button on "New Event" doesn't register the event. So no events get displayed under the ring Dashboard

**Comment by kpamela** [comment]
honestly stumped on this one. I thought it had something to do with the duplicate file in both the "client" and the "collections" folder. Changed a few import names that were not matching and attempted to export "Events", nothing is working ._.

**Comment by tusmanakhter** [comment]
I will be taking a look at this issue
