### ISSUE TITLE
#3 Find a Domain 

### ISSUE THREAD

**Issue by Lordofsnails** [kpamela/StudyRing#12]
just like the title says.

**Comment by 85Arshad** [comment]
Domain found, studyring.tk

**Comment by taj-ch** [comment]
I have reopened this issue. I made a change into the domain name, it's now www.studyring.ml
The hosting server will be discussed on this issue [#24](https://github.com/kpamela/SOEN-341-Project/issues/24)

**Comment by CodeTaj** [comment]
This issue is now closed
