### ISSUE TITLE
[Story] Forgotten Password

### ISSUE THREAD

**Issue by Zackkogan** [kpamela/StudyRing#26]
I would like to be able to recover my account password so that I can still access my account even if I forget the password.
*Priority:* 2
*Story Points*: 3
- [x] Forgot password option under login (HTML)
- [x] Recovery system

**Comment by Zackkogan** [comment]
Rather then recover the password, the system will reset it and send the user the reseted password via entered email for security reasons. Clicking the "forgot password?" link will redirect users to a forgotpassword page in which they can enter their username and/or email and the password will be reset.
Also it needs to be discussed if the forgotpassword page will have login features on the page itself or link to the login page (or both).

**Comment by kpamela** [comment]
Which pull request is this update?

**Comment by Zackkogan** [comment]
i committed directly to master since all i did was add a file and change a href link to the new file (it was placeholder symbol prior to the commit)

**Comment by tusmanakhter** [comment]
Users can now recover their passwords.

**Comment by Zackkogan** [comment]
Tests on #26 passed for #125
