### ISSUE TITLE
[Story] Study Events

### ISSUE THREAD

**Issue by kpamela** [kpamela/StudyRing#39]
As a group admin, I would like to create study events for my group to know when to meet up.

Functionalities to implement
- [x] Create event
*Priority:* 2
*Story points:* 3
- [x] Set event date and time
*Priority:* 2
*Story points:* 1
- [x] Create a private or public attribute for the event (for later use)
*Priority:* 2
*Story points:* 1

Total points: 5

**Comment by kpamela** [comment]
#71

**Comment by Zackkogan** [comment]
All testing on this issue for #125 have been completed
