### ISSUE TITLE
[Story] Study event location

### ISSUE THREAD

**Issue by kpamela** [kpamela/StudyRing#43]
As a group admin, I would like to be able to set the location for a study event so that other members know where we are meeting up.

Story points: 4
Priority: 2
Risk: 1
Estimated hours: 1

**Comment by tusmanakhter** [comment]
New stories should not be in sprint 5, moving this to sprint 4.

**Comment by Zackkogan** [comment]
made a pull request with code to (hopefully) fix the issue.

**Comment by Zackkogan** [comment]
issue solved with #119
