### ISSUE TITLE
Routing to other pages

### ISSUE THREAD

**Issue by kpamela** [kpamela/StudyRing#49]
Links to other pages such as Contact, Github, About, etc. missing.

**Comment by Lordofsnails** [comment]
integrating laurie'  code kinda struggling a bit, just a little

**Comment by Lordofsnails** [comment]
you know what, we did this wrong lol, we should code stuff on the same goddam folder lol, and then we do css styling and all, now them variable conflicts are killing me

**Comment by tusmanakhter** [comment]
Routing works fine. It can be refactored in sprint 4 or 5.
