### ISSUE TITLE
Ring Layouts need to be corrected

### ISSUE THREAD

**Issue by kpamela** [kpamela/StudyRing#73]
- Rings on the sidenavs should bring to a list of my rings, right now it only shows how to create a "new ring"
- After a New ring is created, it must be possible to exit the editor mode, right now it is getting stuck in that position
- Rings must only have a "delete" option under My Rings, not in the browse rings (will become a permission issue)

**Comment by kpamela** [comment]
Working progress on Pam4.0 Branch

**Comment by kpamela** [comment]
Rings.html now encompasses all the other ring templates. 
*- Rings template and all subtemplates
-RingInfo - RingSingle -RingDash
{{Rings}} displays all rings if it is open under the "Browse Rings" session, or only your rings if it is open in the "My Rings" session Pam4.0 branch

**Comment by tusmanakhter** [comment]
Auto-closing of the New Ring form after it is created is not completed yet, I will be working on it.
