### ISSUE TITLE
Created by user => isMember

### ISSUE THREAD

**Issue by kpamela** [kpamela/StudyRing#78]
A user who creates a ring is not member of his own ring by default

**Comment by tusmanakhter** [comment]
I am fixing this bug as well as removing the ring Id from all users who are in a ring that is being deleted.

**Comment by tusmanakhter** [comment]
This has been corrected and pushed on to [Testingbranch](https://github.com/kpamela/StudyRing/tree/TestingBranch), I will request a pull request later.
