### ISSUE TITLE
[STORY] Forum For Study Groups

### ISSUE THREAD

**Issue by taj-ch** [kpamela/StudyRing#80]
I would like to communicate with other members of my ring through a forum.
- [x] Create a collection for the forum
- [x] Front-End for the forum postings
- [x] Template for the the forum 

Story Points: 15
Priority: 2
Risk: 2
Estimated hours: 15

**Comment by tusmanakhter** [comment]
Linking of comments to a ring instead of a general forum will be the next task as well as uploading files.
