### ISSUE TITLE
[STORY] Joining Private Study Groups

### ISSUE THREAD

**Issue by taj-ch** [kpamela/StudyRing#82]
As a student, I would like to join a private study group made by a member I know eg. friend, family, teacher, TA.

- [x] Clicking Join on a private study group will prompt a password
- [x] Password safety handlers
- [x] Correct password allows user to join

Story Points: 5
Priority: 2
Risk: 1
Estimated hours: 6

**Comment by Lordofsnails** [comment]
Also if I am editing rings, how many files do I have to change? 

The collection
   - rings.js (add the password section)
   -methods.js ( add ring.update and set password) 

Template 
-newRing.html
-ring.hrml 
And the js files accordingly with an alert
Prompt an input and an if true statement to add the member
Is this logic fine? Or I need more things and have to edit more files?

**Comment by tusmanakhter** [comment]
The logic seems to be fine and I think those are all the files you need to edit.

But, I don't get what will the ring.update method do, we already allow the ring Owner to edit (update) the ring.

**Comment by Lordofsnails** [comment]
So i used a modal system, but the thing is it is continuously crashing...i ll try and fix it tomorrow, my brain is dead at this moment, so i basically tried to play smart and integrated everything into the toggle-private method... so when you click on it, i run a _model.show <I basically render a template/pop up when you toggle private>   

but i think its the way i store the files, or variable that isn t right...anyway i ll show it to you guys tomorrow

**Comment by Lordofsnails** [comment]
worked 8 hours so far (changed my own code many times) with procrastination time included probably... lel

**Comment by Lordofsnails** [comment]
If not fixed by 6 pm, i ll just change do a lame thing that works, but probably not so secure...

**Comment by Lordofsnails** [comment]
After working for another 5 hours, at least, i got the prompt user to enter password when joining a private group done, but i have some problems with the logic behind

**Comment by kpamela** [comment]
#105 Adds this functionality

**Comment by kpamela** [comment]
Still not prompting user to enter password when he joins a private study ring.

**Comment by Lordofsnails** [comment]
add another 8 hours for figuring out the bug out
