### ISSUE TITLE
[STORY] Creating permissions

### ISSUE THREAD

**Issue by kpamela** [kpamela/StudyRing#90]
As a group creator, I would like to have exclusive permission to manage my ring.

Description: Any user can edit any group created, which is not desirable. Also, Ring templates should adapt to the status of the user (owner or not).

- Templates for front end must be changed according to permissions #92 

Story points: 5
Priority: 1 
Risk: 1

**Comment by tusmanakhter** [comment]
I have set up permissions for various functions while I was writing tests for those functions. All issues regarding permissions should have been corrected and are on the [Testingbranch](https://github.com/kpamela/StudyRing/tree/TestingBranch).

**Comment by kpamela** [comment]
@tusmanakhter I tested it and it with two different accounts, it's still displaying  both under "Rings" I fixed it under Pam 4.0 though
