### ISSUE TITLE
front-end -> duplicated avatar feature

### ISSUE THREAD

**Issue by kpamela** [kpamela/StudyRing#93]
I've just notivced this, I thin there's something duplicated in the css/styl files but I'm not sure where.
![image](https://cloud.githubusercontent.com/assets/24784649/24058717/946e997a-0b22-11e7-8039-b97023d6057c.png)

**Comment by tusmanakhter** [comment]
Nothing is duplicated here. The Default Avatar sections allows users to quickly switch to the default avatar if they are using a custom avatar. It is hidden if the user is already using the default avatar.
